spring:
  application:
    name: Surfstation Easy Edit
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/easyedit
    username: easyedit
    password: easyedit
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

data:
  users: surfstation, engelsborg, houhavn, saebyhavn, skagenhavn, lynettenhavn, helsingoerhavn, nykoebinghavn

---

spring:
  profiles: openshift
  datasource:
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
logging:
  file: ${OPENSHIFT_DATA_DIR}/logs/app.log
  level: INFO

---

spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

---

spring:
  profiles: docker
  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/easyedit
    username: easyedit
    password: easyedit
server:
  port: 80

---

spring:
  profiles: https
server:
  port: 8443
  ssl:
#    key-store: src/main/resources/keystore.p12
    key-store: /etc/letsencrypt/live/easyedit.surfstation.dk/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl: true

---

spring:
  profiles: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

