spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}

logging:
  file: ${OPENSHIFT_DATA_DIR}/logs/app.log
  level: INFO
