spring:
  application:
    name: Surfstation Easy Edit
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/easyedit
    username: easyedit
    password: easyedit
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

---

spring:
  profiles: openshift
  datasource:
    platform: postgres
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}

logging:
  file: ${OPENSHIFT_DATA_DIR}/logs/app.log
  level: INFO
