version: '2'

services:
  backend:
#    build:
#      context: ../../../target/docker
#      dockerfile: Dockerfile
    image: easyedit
    container_name: surf-easyedit-backend
    ports:
      - 8080:80

  db:
    image: postgres:9.6-alpine
    container_name: surf-easyedit-db
    environment:
      - POSTGRES_USER=easyedit
      - POSTGRES_PASSWORD=easyedit
#      - POSTGRES_DB=easyedit
    volumes:
      - surf-easyedit-db:/var/lib/postgresql/data

# https://gist.github.com/hernandev/14b31358338a5bbe01eb023fd922656c
# https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
  frontend:
    image: nginx:stable-alpine
    container_name: surf-easyedit-frontend
    volumes:
      - ../../../src/main/resources/static/my-project/dist:/var/www
    ports:
      - 8081:80

volumes:
  surf-easyedit-db:
